Fix 'logging.py' name clash with Python's built-in logging module
logging.py:
- change: refactor/rename logging.py to custom_logging.py to solve circular import errors ("AttributeError": module 'logging' has no attribute 'getLogger'"), which made debugging and implementing new features unnecessarily hard

tree.py:
- fix: optimized imports (vulture complained about imported, but never used modules)

quality_matrix.py:
- fix/logging: Exception variable 'e' was caught, but never logged or used (this fixes vulture F841)